AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM app with PostgreSQL, DynamoDB, TypeScript & Python Lambdas.

Globals:
  Function:
    Timeout: 10

Resources:
  MentalInsightsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_mental_insights.lambda_handler
      Runtime: python3.11
      CodeUri: .
      Events:
        MentalInsightsApi:
          Type: Api
          Properties:
            Path: /mental-insights
            Method: GET



Outputs:
  ApiUrl:
    Description: "API Gateway endpoint"
    Value:
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user"
